name: Build conda package and upload to Anaconda.org

on:
  push:
    tags:
      - 'conda-build/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up micromamba (Linux)
        if: runner.os == 'Linux'
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: build-env
          create-args: >-
            python=${{ matrix.python-version }}
            rattler-build
            compilers
            sysroot_linux-64=2.17
            cmake
            make
            triqs

      - name: Set up micromamba (macOS)
        if: runner.os == 'macOS'
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: build-env
          create-args: >-
            python=${{ matrix.python-version }}
            rattler-build
            compilers
            cmake
            make
            triqs

      - name: Build Conda Package
        id: build
        shell: "bash -l {0}"
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
             eval "$(micromamba shell hook --shell=bash)"
             micromamba activate build-env

             BUILD_ARGS="
                --recipe packaging/conda/recipe.yaml
                --output-dir ${HOME}/output
             "
             if [[ "$RUNNER_OS" == "macOS" ]]; then
                BUILD_ARGS="${BUILD_ARGS} -m packaging/conda/variants-osx.yaml"
             fi

             rattler-build build ${BUILD_ARGS}

      - name: Upload package to Anaconda
        shell: "bash -l {0}"
        env:
          ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
             # Get the path to the built packages from the output folder
             BUILT_PKG=$(find "${HOME}/output" -type f -name "*.conda")
             BUILT_PKG=$(echo ${BUILT_PKG} | tr '\n' ' ')
             echo "Built packages: ${BUILT_PKG}"

             rattler-build upload anaconda -f -o krivenko ${BUILT_PKG}
